### ISSUE TITLE
Unexpected behavior with function refs on animated elements

### ISSUE THREAD

**Issue by EECOLOR** [pmndrs/react-spring#1037]
## 🐛 Bug Report

A functional ref is called 2 times on initial render and 4 times on a re-render. 2 of the 4 are with a `null` value.

A normal (non `animated`) `div` results only in a single call.

## To Reproduce

```jsx
import { animated } from 'react-spring'

export default function App() {
  const [bool, setBool] = React.useState(false)
  const ref1 = React.useCallback(node => { console.log('ref1', node) }, [])
  const ref2 = React.useCallback(node => { console.log('ref2', node) }, [])
  return (
    <div>
      <div ref={ref1}>1</div>
      <animated.div ref={ref2}>2</animated.div>
      <button onClick={() => setBool(x => !x)}>Rerender</button>
    </div>
  )
}
```

Output on first render is this:
```
ref1 <div>​1​</div>​
ref2 <div>​2​</div>​
ref2 <div>​2​</div>​
```

On subsequent clicks:
```
ref2 null
ref2 null
ref2 <div>​2​</div>​
ref2 <div>​2​</div>​
```

Live example: https://codesandbox.io/s/nervous-hugle-u7unw?file=/src/App.js

## Expected behavior

I expect the `animated.div` to behave the same as a `div` when it comes to `ref`.

## Link to repro (highly encouraged)

https://codesandbox.io/s/nervous-hugle-u7unw?file=/src/App.js

## Environment

- `react-spring` v8.0.27
- `react` v16.12.0

**Comment by joshuaellis** [comment]
Thanks for reporting the bug, unfortunately, due to resourcing & maintainer change overs there’s no one able to work on v8 so we’re freezing development on it. However, you’re welcome to supply a fix on the v8 branch if you’d like. If the issue remains in v9 then please reopen a new issue, but bare in mind it might be quicker still to provide your own fix and contribute.
