### ISSUE TITLE
[BUG] TS2554: Expected 1 arguments, but got 2.

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [pmndrs/react-spring#1166]
> "react-spring": "^8.0.27",
> "typescript": "^4.0.3",

![image](https://user-images.githubusercontent.com/69426460/95029437-ee7b4980-06b0-11eb-8d16-9721a3e550af.png)

![image](https://user-images.githubusercontent.com/69426460/95029457-166aad00-06b1-11eb-9aa6-8d63d8c6fe65.png)

**Comment by joshuaellis** [comment]
Thanks for reporting the bug, unfortunately, due to resourcing & maintainer change overs there’s no one able to work on v8 so we’re freezing development on it. However, you’re welcome to supply a fix on the v8 branch if you’d like. If the issue remains in v9 then please reopen a new issue, but bare in mind it might be quicker still to provide your own fix and contribute.
