### ISSUE TITLE
[BUG] TS2769: No overload matches this call.

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [pmndrs/react-spring#1167]
"react-spring": "^8.0.27",
    "typescript": "^4.0.3",

```ts
  const props = useSpring({
    from: { transform: 'translate(-10em, 0em) rotateZ(0deg)' },
    to: [
      { transform: 'translate(10em, 0em) rotateZ(-10deg)' },
      { transform: 'translate(5em, 5em) rotateZ(10deg)' },
      { transform: 'translate(-5em, 15em) rotateZ(-20deg)' },
      { transform: 'translate(-10em, -1em) rotateZ(90deg)' },
      { transform: 'translate(10em, 1em) rotateZ(-70deg)' },
    ],
  })
```

![image](https://user-images.githubusercontent.com/69426460/95034321-00b5b180-06ca-11eb-9a33-e89cf0ad8dce.png)

![image](https://user-images.githubusercontent.com/69426460/95034326-09a68300-06ca-11eb-8e45-cc49acf46cb1.png)

![image](https://user-images.githubusercontent.com/69426460/95034391-5722f000-06ca-11eb-9801-21ee1df5dc30.png)

**Comment by joshuaellis** [comment]
Thanks for reporting the bug, unfortunately, due to resourcing & maintainer change overs there’s no one able to work on v8 so we’re freezing development on it. However, you’re welcome to supply a fix on the v8 branch if you’d like. If the issue remains in v9 then please reopen a new issue, but bare in mind it might be quicker still to provide your own fix and contribute.
