### ISSUE TITLE
Typescript error when interpolating array

### ISSUE THREAD

**Issue by omasback** [pmndrs/react-spring#1175]
## 🐛 Bug Report

Interpolating an array results in type error regarding param mismatch in interpolate callback.

## To Reproduce

try to interpolate an array value from `useSpring`, as in the xyz vector example in the docs. Results in type error: `Argument of type '(x: any, y: any, z: any) => string' is not assignable to parameter of type '(params: number[]) => string'.ts(2769)` The code still works. It's a false error.

## Expected behavior

No type error

## Link to repro (highly encouraged)

https://codesandbox.io/s/react-spring-array-interpolate-typescript-error-tjslr

## Environment

- `react-spring` v8.0.27
- `react` v16.13.1

**Comment by chayeoi** [comment]
I get the same error.

**Comment by marianayap** [comment]
@omasback  Hello! could I work in the issue or is already assigned?

**Comment by joshuaellis** [comment]
> @omasback Hello! could I work in the issue or is already assigned?

Go right ahead, more than welcome.

**Comment by joshuaellis** [comment]
Thanks for reporting the bug, unfortunately, due to resourcing & maintainer change overs there’s no one able to work on v8 so we’re freezing development on it. However, you’re welcome to supply a fix on the v8 branch if you’d like. If the issue remains in v9 then please reopen a new issue, but bare in mind it might be quicker still to provide your own fix and contribute.
