### ISSUE TITLE
Specify the height of a "page" in the Parallax component

### ISSUE THREAD

**Issue by chrispytoes** [pmndrs/react-spring#1217]
## 🚀 Feature Proposal

Add the ability to specify how tall a "page" is in the `Parallax` component. Currently, each page is assumed to be `100vh`, but what if there's a sticky header at the top? Then the page height should be `calc(100vh - headerHeight)`.

## Motivation

I have a `Parallax` component in a page which has a sticky header, so the page content has an 84px top margin to compensate. As a result, the Parallax scroller is 84px too tall, and the bottom of the content is cut off when scrolled to the bottom. I need to make the `Parallax` component treat one page as `calc(100vh - 84px)` instead of `100vh`.

## Example

```
<Parallax
	pages={3}
	scrolling={true}
	horizontal={false}
        pageHeight={window.innerHeight - 84}
>
```

**Comment by kindoflew** [comment]
This is straightforward to implement, but the height of a page will actually default to whatever height the outer container of `Parallax` is. The default is `100%`, but you can override it. So I'm pretty sure this can already be achieved with something like this:

```jsx
<Parallax style={{ height: 'calc(100% - 84px)', top: '84px' }}>
...
</Parallax>
```
(You can set `top` because the outer container is `position: absolute` by default. I suppose you could also override that to `position: relative`, just don't do `position: static` because that would probably break the positioning of the inner container.) 

Would this solve your issue, @chrispytoes ?

**Comment by chrispytoes** [comment]
@kindoflew I actually closed the issue before because I came to that exact realization, thanks.

**Comment by joshuaellis** [comment]
Sorry @chrispytoes that was my bad, but at least now there's an answer incase someone else wants to know how to do it!
