### ISSUE TITLE
SVG filters like <animated.filter> or <animated.feGaussianBlur> don't work

### ISSUE THREAD

**Issue by MartinJaskulla** [pmndrs/react-spring#1305]
## 🐛 Bug Report

When I put `animated` on svg filter elements I get the error `Element type is invalid: expected a string (for built-in components)`

## Link to repro

Set renderBug to true
https://codesandbox.io/s/fervent-dubinsky-wq0zv?file=/src/index.js

## Environment

- `react-spring` v8.0.5 and v8.0.27
- `react` v16.8.1 and v17.0.1

**Comment by joshuaellis** [comment]
Thanks for reporting the bug, unfortunately, due to resourcing & maintainer change overs there’s no one able to work on v8 so we’re freezing development on it. However, you’re welcome to supply a fix on the v8 branch if you’d like. If the issue remains in v9 then please reopen a new issue, but bare in mind it might be quicker still to provide your own fix and contribute.
