### ISSUE TITLE
Wrong transition phase inside the transition callback

### ISSUE THREAD

**Issue by pauldijou** [pmndrs/react-spring#1410]
## 🐛 Bug Report

The `transition` callback is called with the wrong Transition phase. This feels like a bug to me but maybe I'm missing something.

## To Reproduce

From the linked codesandbox, if you pop an item from the array, you will see that `transition` is called at phase `enter` and the component is rendered with that phase (the text inside the `div`). It seems strange as the item is actually leaving the transition.

Soon after, the `Transition` object will move to the `leave` phase (I observed that by plugging a `console.log` into the `to` function of the `SpringValue`) but it seems a bit late if you wanted to react to Transition phase changes (like saving the height of the component before removing it so that you can animate it properly).

## Expected behavior

I would expect the `transition` callback to be invoked with the proper Transition phase. If an item is leaving, the function should be called at least once with the `leave` phase.

## Link to repro (highly encouraged)

https://codesandbox.io/s/focused-tdd-1rjw4?file=/src/App.js

## Environment

- `react-spring` v9.1.0
- `react` v17.x.x

**Comment by joshuaellis** [comment]
So, this is how our `useTransition` phase system currently works – i'm not saying it's right though.

We have a in-render function that creates our `changes` this includes the new phase we're going to, the springs and a payload (normally controller props). We set this like so (t, is your item):

```js
changes.set(t, { phase, springs, payload })
```

The initial state is for transitions is `mount` and the `render` function is called, hence why the first item is stuck on `mount` even though it's entered.

We then go through the `changes` in a `useLayoutEffect` so this is how it actually animates and we update the phase accordingly. But this doesn't cause a re-render, again why item 0 still says `mount`. But internally updates is phase to `enter` which is why the `to` function can see the correct phase.

We can move setting the phase into the inline function that creates the changes, but then you won't receive the `mount` phase. I personally can't think of a use case fo that, but equally, i've never really used the phases.

I'll need to think about how we should proceed. Happy to hear thoughts if you have them.

**Comment by joshuaellis** [comment]
I think no one else seems to be having this issue, so I think i'm going to leave this as is, unless people have strong opinions else someone would like to create a PR...
