### ISSUE TITLE
onStart and onRest callbacks not invoked when immediate is true

### ISSUE THREAD

**Issue by pauldijou** [pmndrs/react-spring#1419]
## 🐛 Bug Report

`onStart` and `onRest` callbacks are not invoked for `immediate: true` animations when using `useSpring` except if using the new [Events props](https://aleclarson.github.io/react-spring/v9/#Event-props) syntax.

## To Reproduce

Create a `useSpring`, assign a function to the `onRest` property and set `immediate: true`. The function won't be called at the end of the animated. Only one `onChange` is invoked. When using "Events props", all 3 callbacks are invoked.

Using the [1st codesandbox](https://codesandbox.io/s/vigorous-chaum-qvf9m?file=/src/App.js), if you do the exact following:
- reload the sandbox (to have a clean state)
- toggle opacity (text is gone)
- toggle immediate (the animation is no longer immediate)
- toggle opacity

You will see that the animation works fine but, for some reason, both `onStart` and `onRest` are invoked 3 times instead of once. And actually, the more you toggle opacity *before* you toggle `immediate`, the more those both callbacks are going to be invoked.

## Expected behavior

When a value is animated, immediate or not, I'm expecting `onStart` to be invoked, then zero or more `onChange` and finally one `onRest`.

## Link to repro

v9 using a callback (bug):  https://codesandbox.io/s/vigorous-chaum-qvf9m?file=/src/App.js
v9 using "Event props": https://codesandbox.io/s/youthful-resonance-i3xxq?file=/src/App.js
v8 using a callback: https://codesandbox.io/s/jolly-shadow-v3jvv?file=/src/App.js

## Environment

- `react-spring` v9.1.1
- `react` v17.x.x`

**Comment by joshuaellis** [comment]
Thanks for the report, I find the side notes a little confusing. It sounds like SideNote2 could be a different issue or rather if you want us to look at it it may benefit from it's own issue?

SideNote1, i think this is because the events aren't being flushed. They should be called just like in the `EventProps` example, so they're added to the Map stack and only flushed when we turn `immediate` off.

**So, to simplify what I think the issue is (for when I eventually look at it, or maybe someone else does):**

Events `onStart` & `onRest` are not called if `immediate` is `true`, as seen in the first [sandbox]( https://codesandbox.io/s/vigorous-chaum-qvf9m?file=/src/App.js). This causes a build up of event queues in `Controller` (and potentially `SpringValue`). When `immediate` is set to `false` the built up queue is cleared, calling the entire event stack. These "old" events have the same `AnimationResults` passed to them (at least a small phew).

**Comment by pauldijou** [comment]
You're right. I removed the 2nd side note and created a separate issue.
