### ISSUE TITLE
transform: translateX(calc(100% + 10px)) can't work

### ISSUE THREAD

**Issue by KennethKinLum** [pmndrs/react-spring#1446]
## 🐛 Bug Report

`transform: translateX(calc(100% + 10px))`   would not move to the expected 70px, but 100px 
(probably taking the 100% to mean 100px)

## To Reproduce

https://codesandbox.io/s/hopeful-wind-d5es0?file=/src/App.js
And then click on the "Slide Right" button.

we can see it actually moves to 100px, instead of 100% + 10px, which is 70px

## Expected behavior

should move to calc(100% + 10px), which is 70px

## Link to repro (highly encouraged)

https://codesandbox.io/s/hopeful-wind-d5es0?file=/src/App.js

## Environment

- `react-spring` v9.1.x
- `react` v16.8.x (or `react-native` v0.58.x)

**Comment by chrissantamaria** [comment]
I may be missing something, but this seems out of the scope of react-spring (more specifically, the underlying `AnimatedString` class). I'm not sure what the per-frame `transform` values should be in this case.

In an ideal world, react-spring would animate from `translateX(0px)` to `translateX(70px)`. This is tricky to implement since it would require calculating the 70px goal based on the `calc` expression which likely involves measuring the target element (probably not feasible here). From my understanding, there ultimately needs to be some sort of numeric animation goal which I'm not quite sure how to obtain here.

As a workaround, could you do the element measurement yourself in order to set a more defined `transform` value? Something like this: https://codesandbox.io/s/xenodochial-sky-em0w3?file=/src/App.js

**Comment by joshuaellis** [comment]
I think the correct way to do this would be to use something like `useMeasure` to measure the dom element.
