### ISSUE TITLE
useChain does not run hooks in sequence when duration is specified

### ISSUE THREAD

**Issue by arteforme** [pmndrs/react-spring#1492]
## 🐛 Bug Report

If a `duration` is specified in a config for an animation hook that is supplied to `useChain`, any hooks defined after it will not wait for the `duration` to elapse. Instead, they'll run soon after the hook, w/ the `duration` specified, starts.

## To Reproduce

1.  Define 2 or more hooks to supply to `useChain`.  At least one of the hooks should define a `duration` in its config.
2. Call `useChain` and supply the hooks, defined in step 1, such that the hook, with a `duration`, comes before at least one hook that does not have a `duration`.  For example:  `useChain([hookA, hookB, hookWithDuration, hookC, etc.])`

## Expected behavior

Hooks that are declared after the hook that defines a `duration` wait for the `duration` to elapse before starting their animation.  In the pseudo code above, `hookC` does not start until `hookWithDuration` finishes.

## Link to repro (highly encouraged)

* v8 [code sandbox](https://codesandbox.io/s/happy-feynman-s9beo?file=/package.json)  where hooks are running in sequence (expected)
* v9 [code sandbox](https://codesandbox.io/s/peaceful-germain-u322l?file=/src/index.js) where hooks are running sequentially without waiting for the previous hook to finish. (bug)

Both are forked from [original](https://codesandbox.io/embed/2v716k56pr)

## Environment

v8:

* "react": "16.8.0",
* "react-dom": "16.8.0",
* "react-scripts": "2.0.3",
* "react-spring": "8.0.1",
* "styled-components": "4.1.2"

v9:

* "react": "17.0.1",
* "react-dom": "17.0.1",
* "react-scripts": "4.0.3",
* "react-spring": "9.1.2",
* "styled-components": "5.3.0"

**Comment by limekiln** [comment]
I might be kind of hijacking this issue, but maybe it is related ...
It seems `useChain` does also not play animations sequentially when using the `set` function of `useSpring`. Or at least I cannot get it working. Since I need to configure the spring once the DOM is loaded (translation based on height of an element), I do this using `set` in a `useEffect` hook. Following the given examples otherwise, the `useChain` hook seems to have no effect at all.

Is there another way to handle configuration of springs with DOM element values and might the chain behaviour be related to this issue?

**Comment by joshuaellis** [comment]
Hello!

I've pushed a fix as `9.2.6-beta.0` please let me know if this resolves your issue 😄
