### ISSUE TITLE
useChain with useSpring behaves unexpectedly in Chrome & Edge

### ISSUE THREAD

**Issue by sapinder-pal** [pmndrs/react-spring#1549]
## 🐛 Bug Report

I made a `ThemeToggler` button which contains an SVG. This SVG toggles between the Moon and Sun with an animation. It works fine in Firefox & Opera Mini, but doesn't work properly in Chrome, Brave and Edge.

## Expected behavior

The Sun, when dark mode is enabled, scales down to 0 & the moon scales up to 1. The opposite is supposed to happen when dark mode is disabled. But the Sun shows up without any animation after a delay. **This is only the case with browsers other than Firefox & Opera Mini**

## Link to repro

I made a [CodeSandbox Demo](https://codesandbox.io/s/react-spring-repro-bt889?file=/src/MoonOrSun.jsx) to reproduce the animation. Try to observe it when switching from dark mode to light mode.

## Environment

The packages' versions are there in the codesandbox demo
- Chrome v91.0.4472.77
- Firefox v89.0
- Edge v91.0.864.41
- Brave v91.1.25.70

**Comment by joshuaellis** [comment]
This is probably a Chrome issue, if you change the prop from `style` to `transform` it works fine. Since Edge is now basically a MS clone of Chrome I would suspect it too.

Here's a working sandbox where i've used `transform` instead of the `style` attribute – https://codesandbox.io/s/react-spring-repro-forked-nj0s9
