### ISSUE TITLE
useTransition does not run  "leave" transition when delay is set

### ISSUE THREAD

**Issue by camurai** [pmndrs/react-spring#1662]
## 🐛 Bug Report

the useTransition hook does not run the "leave" transition if a delay is set. This can be seen in action on the "Toggle between components" example in the documentation for useTransition here: [useTransition Documentation](https://react-spring.io/hooks/use-transition#mountunmount-single-component-reveals)

The emoji abruptly disappears before the new one fades in, instead of slowly fading out as intended.
 
## To Reproduce
copy the "Toggle between components" example from  [useTransition Documentation](https://react-spring.io/hooks/use-transition#mountunmount-single-component-reveals)

Code Sandbox: https://codesandbox.io/s/zealous-wiles-tehw6?file=/src/App.js

if you remove the delay setting, the two will fade in and out as expected (though of course without the delay)

## Expected behavior
smooth animated transition between the two components including a fade out.

## Environment

- `react-spring` v9.2.4
- `react` v17.0.2

**Comment by joshuaellis** [comment]
Thanks for the report! I would ask that you provide a minimal code sandbox example for us to review the bug. Thanks!

**Comment by camurai** [comment]
code sandbox added. https://codesandbox.io/s/zealous-wiles-tehw6?file=/src/App.js

**Comment by Aaron-Storm** [comment]
Is there any update in this regard or any information if this bug will be fixed soon as otherwise I will have to find a workaround for the time being. The bug affects every "leave" transition and is pretty obvious in every example shown in the docs. Thanks for your time.

**Comment by joshuaellis** [comment]
@Aaron-Storm respectfully, I think you're under the illusion there are a team of developers maintaining `react-spring` day to day, unfortunately, this is simply not the case. We rely on a community to fix bugs in OSS, i have a full-time job and do this on the side when I have time, sadly recently I haven't had this time as i have a few large projects on at work that require my full attention during and out of hours.

However, I am more than happy to support other people provide fixes for the issues they face, including yourself, as this just requires me sharing knowledge & writing.

**Comment by Aaron-Storm** [comment]
My apologies, I did not mean to come over as disrespectful. I was just wondering if there is any update just so I know if it's worth spending time to find another workaround. 
Thanks for the clarification though and again thanks for your time. Much appreciated.

**Comment by joshuaellis** [comment]
> @joshuaellis My apologies, I did not mean to come over as disrespectful. I was just wondering if there is any update just so I know if it's worth spending time to find another workaround. 
> 
> Thanks for the clarification though and again thanks for your time. Much appreciated. 

No worries, like i said, you might have better luck solving the issue as opposed to looking for a workaround 🥸

**Comment by AndriesVDW** [comment]
It seems like 9.2.0-beta.4 is the update that breaks it. It still works properly in 9.2.0.-beta.3.

**Comment by joshuaellis** [comment]
> It seems like 9.2.0-beta.4 is the update that breaks it. It still works properly in 9.2.0-beta.3.

Thanks for this, this will be helpful for anyone looking to solve the issue ⭐

**Comment by AndriesVDW** [comment]
When removing `propsDelay` from [this](https://github.com/pmndrs/react-spring/compare/v9.2.0-beta.3...v9.2.0-beta.4#diff-3dce88b788d6e5008705461509e6c3a027695ca9a198d918b9d9c4800d4d2181R242) line, the transition works the way it did before.

When I change the version of the [example](https://codesandbox.io/s/peaceful-sutherland-7ldio?file=/src/App.js) to 9.0.0 and increase the delay to say, 5000, it ignores the delay. Did this ever work?

I know this doesn't realy fix it, but maybe this will be helpfull to someone as well.

**Comment by joshuaellis** [comment]
Thanks again for the research. I've been looking and I can see the issue we're having and I'm going to write it down so I don't forget the next time I find time to look at this so here it goes.

delays are attached in the `scheduleProps` function where we make our paused, resume queues because scheduleProps is called in a `raf` loop. But the specific call to scheduleProps is from a `SpringValue` so that classes' `_state` has the information that we're actually paused and waiting for something (the delay). 

However, the `Controller`'s state doesnt have the information that it's springs are paused (this is the problem // bug) so when when we call `onResolve` in the `useTransition` hook the `Controller` is seen as idle, it's then removed and `forceUpdate` is called thus cleaning out the transitions array removing the item. 

This wouldn't happen normally because the state update would cause the springs to begin animating thus the `Controller` would not be `idle`.

So I think a solution to look into is, can the Controller be safely `"paused"` whilst it's springs are, can springs value different delays (I don't think so, maybe when its a `useSpring`?)? Or do we need to bubble up this state so the Controller's state reflects such knowledge...... 🤔

**Comment by joshuaellis** [comment]
This has been released on `v9.4.0-beta.4`
