### ISSUE TITLE
[bug]: ParallaxLayer offset not working as intended when using speed other than 0

### ISSUE THREAD

**Issue by Deaponn** [pmndrs/react-spring#1895]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.4.5

### What's Wrong?

When using ParallaxLayer, the offset property does not work when speed is set to any other value than 0, leaving blank spaces with height of entire screen between the ParallaxLayer's

### To Reproduce

1. npx create-react-app
2. npm install @react-spring/parallax
3. Replace App.js with the code that was supplied in the Codesandbox

### Expected Behaviour

No blank spaces between ParallaxLayer components, consistent background

### Link to repo

https://codesandbox.io/embed/fancy-snowflake-bsl56n?fontsize=14&hidenavigation=1&theme=dark

**Comment by kindoflew** [comment]
hi!

this *is* working as intended:

the `offset` prop on a `ParallaxLayer` is where it will end up when scrolled to that offset -- ie, if your `ParallaxLayer` has `offset={1}`, it will take up the entire viewport when you scroll the `Parallax` component to the second page (zero-indexed, so the second page is index `1`).

The `rate` prop will affect the starting position of the `ParallaxLayer` -- the higher the `rate`, the further its starting position will be from its `offset` position.

If you wanted your green layer to be touching your red layer in the example, you can go about it two ways:

* set the `offset` of the green layer to `0.99`. this is caused by the motion functions we use internally -- the `offset` prop will decide the initial starting position of a layer in relation to it's rounded down value -- so anything less than one will calculate it in relation to the first `page` of `Parallax` (index `0`), anything above, the second `page` (index `1`).
* instead of a separate `ParallaxLayer`, nest your content inside the first one with `position: absolute` and position it where you'd like it.

Also, if you'd like a solid background color, you can add `style` to `Parallax`.

Hope this helps!

**Comment by Deaponn** [comment]
Hello,
Thanks for help and the explanation,
Sorry for the confusion, I thought about the offset the wrong way
Cheers!

**Comment by Lermatroid** [comment]
Hi, I am running into a similar issue and trying to sort it using the first method you present where you set the offset to 0.99. This seems to work, however I am now trying to add a third page with the offset 1.99 and it is not working. How could I go about adding a 3rd page to this demo? Thanks!
