### ISSUE TITLE
Possible collision with a future built-in React API

### ISSUE THREAD

**Issue by just-boris** [pmndrs/react-spring#847]
React is going to introduce [concurrent mode](https://reactjs.org/docs/concurrent-mode-intro.html) which will include a new [useTransition](https://reactjs.org/docs/concurrent-mode-reference.html#usetransition) hook. However, this library provides a hook with the same name, which is an unfortunate naming collision.

Do you have any ideas or plans how to deal with that?

I opened an issue in the react repo already: https://github.com/facebook/react/issues/17190

**Comment by FredyC** [comment]
Just my 2 cents, I don't think this is a problem. You have plenty of hooks out there with colliding names already. I don't think those should be removed just because React adds something with that name later.

I have seen it in other codebases and we adopted it as well ... just `React.useTransition` and you are golden. I recommend prefixing all React hooks like that.

**Comment by drcmda** [comment]
i agree, and ultimately i hope they're taking that burden off our shoulders: https://github.com/reactjs/rfcs/issues/128
