### ISSUE TITLE
IE 11 support?

### ISSUE THREAD

**Issue by oliviertassinari** [pmndrs/react-spring#877]
## 🐛 Bug Report

```jsx
import { useSpring } from 'react-spring/web.cjs';
```

Crash with

![Capture d’écran 2019-12-02 à 12 12 46](https://user-images.githubusercontent.com/3165635/69955067-19c76200-14fd-11ea-84d7-47e2a4391ab6.png)

## To Reproduce

I have noticed the issue on https://material-ui.com/components/tree-view/#custom-icons-border-and-animation.

![Capture d’écran 2019-12-02 à 12 21 11](https://user-images.githubusercontent.com/3165635/69955581-4465ea80-14fe-11ea-8f51-04a50c6d6a39.png)

## Expected behavior

Work in IE 11 with the cjs bundle, 

> The library comes as an es-module compiled for evergreen browsers with the following browserlist config: >1%, not dead, not ie 11, not op_mini all. If you need to support legacy targets or deal with targets that don't support modules, you can use the commonJS export by simply appending .cjs to your imports.

https://www.react-spring.io/

## Link to repro (highly encouraged)

https://github.com/react-spring/react-spring/blob/26e135ff42e73942785d4f4a1a67d827d26e1e7d/src/useSprings.js#L24

## Environment

- `react-spring` v8.0.27

**Comment by oliviertassinari** [comment]
I'm wondering, would it work with this patch?

```diff
-new Array(length).fill().map((_, i) => { 
+new Array(length).map((_, i) => { 
```

**Comment by codynova** [comment]
I went down the rabbit hole of trying to diagnose why the cjs module wasn't working in IE 11 a couple weeks ago. I don't remember what I finally found after digging through a ton of unrelated issues, but eventually I just added ThreeJS and React-Spring to my build process to be compiled to ES5 with IE 11 support. I'm going to leave a link to the boilerplate repo here in case it's handy for anyone else https://github.com/intouchgroup/react-spring-three-ie11

**Comment by JCTubio** [comment]
Is there any update on this issue? I am using react-spring in a project and it's not working on ie11. I tried with version `8.0.27`, `8.0.4` and `8.0.2` and also using the `.cjs` imports but it still crashes.
I am getting the following console log:

`Object doesn't support property or method 'fill'`

May I suggest the following polyfill as a fix: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill?v=example#Polyfill

**Comment by codynova** [comment]
@JCTubio react-spring is not intended or expected to work on IE11 without transpiling to ES5

You can see an example of a valid ES5 configuration for react-spring and threejs here: [@intouchgroup/react-spring-three-ie11](https://github.com/intouchgroup/react-spring-three-ie11)

Note the usage of Babel and core-js version 3 to transform the react-spring node module

**Comment by JCTubio** [comment]
I managed to solve my issue!
## Background:

I am developing an app using _GatsbyJS_. Gatsby already comes with babel set up so I thought `Array.prototype.fill()` was already being polyfilled and the problem was something else, for example, that node modules were out of babel's scope and so the fix had to be applied to the library, or something like that. **I was wrong.**
Apparently the `Array.prototype.fill()` was not included in the default polyfill from babel.

## Solution

Installing the `gatsby-plugin-polyfill-io` package and configuring it to polyfill `Array.prototype.fill()` solved the issue.
So for anyone else having a similar problem, even if you are not using gatsby I would suggest trying with babel's polyfills.

For anyone else using gatsby, you can find more info on it in the following link:
https://www.gatsbyjs.org/packages/gatsby-plugin-polyfill-io/
